# Generated by Django 4.1.1 on 2022-09-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.TextField(max_length=50)),
                ('Category_image', models.ImageField(upload_to='media/categories/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='media/products/')),
                ('item_name', models.CharField(max_length=60)),
                ('Descount_price', models.ImageField(max_length=60, upload_to='')),
                ('Original_price', models.IntegerField()),
                ('Qty', models.CharField(max_length=60)),
                ('Discription', models.CharField(max_length=600)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.catagories')),
            ],
        ),
    ]
